### ISSUE TITLE
Not have any core when i add <dependency> to pom.xml

### ISSUE THREAD

**Issue by thuykaka** [ksclarke/solr-jetty-maven#14]
I create a repo local and i add <dependency> to pom.xml ,start maven jetty and no core show,but i delete <dependency>,it work

**Comment by ksclarke** [comment]
Hi, what's the dependency that you're adding to the pom?

**Comment by thuykaka** [comment]
i add :

```
   <dependency>
             <groupId>com.tamedtornado</groupId>
             <artifactId>vn-lucene-analyzer</artifactId>
               <version>1.0.0</version>
    </dependency>
```

and pom.xml of vn-lucene-analyzer:

```
<modelVersion>4.0.0</modelVersion>
<groupId>com.tamedtornado</groupId>
<artifactId>vn-lucene-analyzer</artifactId>
<version>1.0.0</version>

<dependencies>

    <dependency>
        <groupId>vn.hus</groupId>
        <artifactId>nlp-tokenizer</artifactId>
        <version>4.1.1</version>
    </dependency>
    <dependency>
        <groupId>org.apache.lucene</groupId>
        <artifactId>lucene-core</artifactId>
        <version>4.8.0</version>
    </dependency>
    <dependency>
        <groupId>org.apache.lucene</groupId>
        <artifactId>lucene-analyzers-common</artifactId>
        <version>4.8.0</version>
    </dependency>
    <dependency>
        <groupId>junit</groupId>
        <artifactId>junit</artifactId>
        <version>4.11</version>
        <scope>test</scope>
    </dependency>

</dependencies>



<build>
    <plugins>
        <plugin>
            <artifactId>maven-compiler-plugin</artifactId>
            <version>3.0</version>
            <configuration>
                <source>1.7</source>
                <target>1.7</target>
            </configuration>
        </plugin>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-shade-plugin</artifactId>
            <version>2.3</version>
            <configuration>
                <!-- put your configurations here -->
            </configuration>
            <executions>
                <execution>
                    <phase>package</phase>
                    <goals>
                        <goal>shade</goal>
                    </goals>
                </execution>
            </executions>
        </plugin>
    </plugins>
</build>
```

</project>

**Comment by ksclarke** [comment]
I don't see vn-lucene-analyzer in Maven Central so I can't test myself.  I did add the two lucene dependencies into my pom and it still worked. I also don't see nlp-tokenizer in Maven Central so couldn't test that.

My first guess would be a difference in Solr/Lucene versions.  Since your project depends on Lucene 4.8.0 libraries, did you build solr-jetty-maven for that version of Solr?  By default, solr-jetty-maven is configured for version 4.10.4.  You can build it for another version though by supplying solr.version at build time; for instance:

```
mvn -Dsolr.version=4.8.0 clean install jetty:run
```

You don't have to do a clean install each time (if you're not changing anything in solr-jetty-maven) but make sure you use the specific solr.version each time you run it:

```
mvn -Dsolr.version=4.8.0 jetty:run
```

That can be configured in your Maven settings.xml (or other typical Maven location) if you don't want to supply it on the command line all the time.

**Comment by thuykaka** [comment]
vn-lucene-analyzer is a repo maven at local and i want use it with solr.i add 

```
   <dependency>
             <groupId>com.tamedtornado</groupId>
             <artifactId>vn-lucene-analyzer</artifactId>
               <version>1.0.0</version>
    </dependency>
```

and run solr and no see core ,but i delete it work,i was try with another solr,but it will have error.
Sorry my english
It is vn-lucene-analyzer https://github.com/TamedTornado/vn-lucene-analyzer
sorry if I bother you

**Comment by ksclarke** [comment]
Hi, I've now cloned `vn-nlp-libraries` and installed it locally and then cloned `vn-lucene-analyzer` and installed it locally.  Then I add the dependency:

```
<dependency>
  <groupId>com.tamedtornado</groupId>
  <artifactId>vn-lucene-analyzer</artifactId>
  <version>1.0.0</version>
</dependency>
```

to my pom for solr-jetty-maven.  I then run:

```
mvn -Dsolr.version=4.8.0 clean install jetty:run
```

and it comes up and the collection1 core is available. Are you doing something else (creating a different, new core?) or is there something else that I could try to reproduce? Do you get an error or just not see collection1 when solr starts?  If there is an error could you post the error message in here?

**Comment by thuykaka** [comment]
Oh! sorry ! i do it ! thanh you very very much !
close

**Comment by ksclarke** [comment]
Great!
